  version: '3.5'
  services:
    nginx:
      image: nginx
      ports:
       - 80:80
      volumes:
       - /home/samirasouza/projeto/movida/src:/usr/share/nginx/html
       - /home/samirasouza/projeto/movida/configs/nginxphp.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
    php:
      build: .
      volumes: 
        - /home/samirasouza/projeto/movida/src:/usr/share/nginx/html
    mysql:
      image: mariadb
      container_name: mysqlphp
      ports:
        - "3306:3306"
      environment:
       MARIADB_ROOT_PASSWORD: 123456